// Verifies every bundled Quran asset against assets/CHECKSUMS.txt.
//
// The Arabic text and the mushaf assets are never modified — not by script,
// not by hand, not to fix an encoding problem. This check is what makes that
// rule real rather than aspirational. See docs/02-data-sources.md §1.
//
//   dart run tool/verify_checksums.dart
//   dart run tool/verify_checksums.dart --write   # regenerate the manifest
//
// If this fails, do NOT regenerate the manifest to make the build pass.
// Establish why the bytes changed first.

import 'dart:io';

import 'package:crypto/crypto.dart';

const _manifestPath = 'assets/CHECKSUMS.txt';

void main(List<String> args) {
  final manifest = File(_manifestPath);

  if (args.contains('--write')) {
    _write(manifest);
    return;
  }

  if (!manifest.existsSync()) {
    stdout.writeln(
      'verify_checksums: $_manifestPath not found — no assets registered yet. '
      'Created in Batch 0.4.',
    );
    exit(0);
  }

  final failures = <String>[];
  var checked = 0;

  for (final line in manifest.readAsLinesSync()) {
    final trimmed = line.trim();
    if (trimmed.isEmpty || trimmed.startsWith('#')) continue;

    final parts = trimmed.split(RegExp(r'\s+'));
    if (parts.length < 2) {
      failures.add('Malformed manifest line: $trimmed');
      continue;
    }

    final expected = parts.first.toLowerCase();
    final path = parts.sublist(1).join(' ');
    final file = File(path);

    if (!file.existsSync()) {
      failures.add('MISSING  $path');
      continue;
    }

    final actual = sha256.convert(file.readAsBytesSync()).toString();
    checked++;
    if (actual != expected) {
      failures.add(
        'MISMATCH $path\n           expected $expected\n           actual   $actual',
      );
    }
  }

  if (failures.isEmpty) {
    stdout.writeln('verify_checksums: $checked asset(s) verified.');
    exit(0);
  }

  stderr.writeln('verify_checksums: ${failures.length} problem(s)\n');
  for (final f in failures) {
    stderr.writeln('  $f');
  }
  stderr.writeln(
    '\nDo not regenerate the manifest to silence this. Find out why the bytes '
    'changed. See docs/02-data-sources.md §1.',
  );
  exit(1);
}

void _write(File manifest) {
  final assets = Directory('assets');
  if (!assets.existsSync()) {
    stderr.writeln('verify_checksums: no assets/ directory.');
    exit(1);
  }

  final entries = <String>[];
  final files =
      assets
          .listSync(recursive: true)
          .whereType<File>()
          .where((f) => !f.path.endsWith('CHECKSUMS.txt'))
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));

  for (final file in files) {
    final digest = sha256.convert(file.readAsBytesSync());
    entries.add('$digest  ${file.path.replaceAll(r'\', '/')}');
  }

  manifest.writeAsStringSync(
    '# SHA-256 checksums for bundled assets.\n'
    '# Generated by: dart run tool/verify_checksums.dart --write\n'
    '# Regenerating this file to fix a failing build is a mistake.\n'
    '# See docs/02-data-sources.md §1.\n\n'
    '${entries.join('\n')}\n',
  );

  stdout.writeln(
    'verify_checksums: wrote ${entries.length} entries to $_manifestPath',
  );
}
